import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Sidebar from "@/components/sidebar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   

  return (
    <html lang="en">
      <body>
        <Navbar />
         <div className="flex min-h-screen">
      {/* Sidebar */}
      <aside className="w-1/5 bg-gray-900   text-white p-5">
       <Sidebar/>
      </aside>

      {/* Main content */}
      <main className="w-4/5 bg-yellow-100 p-5">
        {children}
      </main>
    </div>
      </body>
    </html>
  );
}
