import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import Sidebar from "@/components/sidebar";
import { FloatingDock } from "@/components/FloatingDock";
import { IconBell, IconHome, IconLayoutDashboard, IconPlus, IconSettings, IconX } from "@tabler/icons-react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

  
const inter = Inter ({
  weight: ["400", "500", "600", "800"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
   
  {/* Menu items for the floating menu */}
  const items = [
    {
      title: "Home",
      icon: <IconHome />,
      href: "/home",
    },
    {
      title: "Dashboard",
      icon: <IconLayoutDashboard />,
      href: "/dashboard",
    },
    {
      title: "Notifications",
      icon: <IconBell />,
      href: "/notifications",
    },
    {
      title: "Settings",
      icon: <IconSettings />,
      href: "/settings",
    },
    {
      title: "Create A Post",
      icon: <IconPlus />,
      href: "/create",
    }
  ]

  return (
    <html lang="en">
      <body>
        <Navbar />

        {/* Main content */}
        <main className="flex w-full min-h-screen bg-gradient-to-br from-gray-50 to-blue-50 text-black pt-20">
            {children}
        </main>

        {/* Floating Menu */}
        <FloatingDock items={items}/>
      </body>
    </html>
  );
}
