import "./globals.css";
import Navbar from "../components/navbar";
import Sidebar from "@/components/sidebar";
import InteractiveBg from "@/components/interactivebg";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   

  return (
    <html lang="en">
      <body>
        <InteractiveBg />
        <Navbar />
        <div className="flex h-139 ">
          {/* Sidebar */}
          <div className="w-1/5 bg-gradient-to-br from-[#87CEEB] to-[#6495ED] text-white p-5 overflow-y-auto h-139">
            <Sidebar/>
          </div>
          {/* Main content */}
          <main className="w-4/5 overflow-y-auto h-139 relative">
            <InteractiveBg />
            <div className="relative z-10">
            {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
